[ALPS07713407] conninfra: fix thermal_zone_of_device_ops build breaks
Follow commit f59ac19b7f44 ("thermal/of: Remove old OF code") to
move to new OF APIs and fix the following build breaks:

conninfra/conn_drv/connv2/src/connv2_drv.c:123:48: error: variable
has incomplete type const struct thermal_zone_of_device_ops
conninfra/conn_drv/connv2/src/connv2_drv.c:335:7: error: call to
undeclared function devm_thermal_zone_of_sensor_register;
ISO C99 and later do not support implicit function declarations
[-Wimplicit-function-declaration]

MTK-Commit-Id: 815147ea25c6c464d9aedfd39307fe025f6377ef

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07713407
Feature: Kernel SI Operation
Change-Id: I825deb8a31db492994e8fe91b0d3ec7ca33c870d