[ALPS07673475] conninfra: fix unannotated fall-through build errors
Fix the following build breaks in one go:

vendor/mediatek/kernel_modules/connectivity/conninfra/conn_drv/connv2/platform/consys_hw.c:222:2: error: unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]
vendor/mediatek/kernel_modules/connectivity/conninfra/conn_drv/connv2/platform/consys_hw.c:228:2: error: unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]
vendor/mediatek/kernel_modules/connectivity/conninfra/base/osal.c:335:23: error: no member named statistics in struct sched_entity
vendor/mediatek/kernel_modules/connectivity/conninfra/base/osal.c:336:21: error: no member named statistics in struct sched_entity
vendor/mediatek/kernel_modules/connectivity/conninfra/conn_drv/connv2/platform/mt6985/mt6985_pmic.c:34:8: error: type specifier missing, defaults to int [-Werror,-Wimplicit-int]

MTK-Commit-Id: 2e7c4e25ed53675747bce7c7f570a2f415b497c1

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: If55435a74166924bd024b29fd314f4baca4ba971